//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XPG_PerformanceTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactSale
    {
        public int SalesKey { get; set; }
        public System.DateTime DateKey { get; set; }
        public int channelKey { get; set; }
        public int StoreKey { get; set; }
        public int ProductKey { get; set; }
        public int PromotionKey { get; set; }
        public int CurrencyKey { get; set; }
        public decimal UnitCost { get; set; }
        public decimal UnitPrice { get; set; }
        public int SalesQuantity { get; set; }
        public int ReturnQuantity { get; set; }
        public Nullable<decimal> ReturnAmount { get; set; }
        public Nullable<int> DiscountQuantity { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
        public decimal TotalCost { get; set; }
        public decimal SalesAmount { get; set; }
        public Nullable<int> ETLLoadID { get; set; }
        public Nullable<System.DateTime> LoadDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual DimProduct DimProduct { get; set; }
        public virtual DimStore DimStore { get; set; }
    }
}
